name: Setup RDP on Linux Runner with FRP

on:
  workflow_dispatch:

jobs:
  setup-rdp:
    runs-on: ubuntu-latest

    steps:
    - name: Install XRDP and Desktop Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y xrdp xfce4 xfce4-terminal
        sudo systemctl enable xrdp
        echo xfce4-session > ~/.xsession
        sudo systemctl restart xrdp

    - name: Set Username and Generate Random Password
      run: |
        # Set username and generate random password
        USERNAME="runner"
        PASSWORD=$(openssl rand -base64 12)
        echo "$USERNAME:$PASSWORD" | sudo chpasswd

        # Log credentials to a file
        echo "Username: $USERNAME" > rdp-credentials.txt
        echo "Password: $PASSWORD" >> rdp-credentials.txt

    - name: Install FRP Client
      run: |
        wget https://github.com/fatedier/frp/releases/latest/download/frp_0.51.3_linux_amd64.tar.gz
        tar -xzf frp_0.51.3_linux_amd64.tar.gz
        sudo mv frp_0.51.3_linux_amd64 /usr/local/frp

    - name: Configure FRP Client
      run: |
        # Create FRP client config
        cat <<EOF > /usr/local/frp/frpc.ini
        [common]
        server_addr = <FRP_SERVER_IP>
        server_port = 7000

        [rdp]
        type = tcp
        local_ip = 127.0.0.1
        local_port = 3389
        remote_port = 6000
        EOF

        # Log tunnel details
        echo "FRP Tunnel Address: <FRP_SERVER_IP>:6000" >> rdp-credentials.txt

    - name: Start FRP Client
      run: |
        /usr/local/frp/frpc -c /usr/local/frp/frpc.ini &

    - name: Display RDP Credentials
      run: |
        echo "=== RDP Login Details ==="
        cat rdp-credentials.txt

    - name: Keep Workflow Running
      run: |
        # Prevent the workflow from completing
        tail -f /dev/null
